### ISSUE TITLE
Last letter disappears in description

### ISSUE THREAD

**Issue by DarthSpot** [AlexW00/StartTreeV2#4]
When i add a new entry to the tree, enter the description and then add the link via copy-paste, the last letter of the Description is not saved. I have to edit the Tree Item again and add the final letter, then press Enter, then its saved.

![Screenshot_20211217_122247](https://user-images.githubusercontent.com/4151368/146537561-4d8fca62-164e-4fed-acff-9c5de7342c78.png)
![Screenshot_20211217_122434](https://user-images.githubusercontent.com/4151368/146537654-8e0d6d78-3856-4049-bb28-35fc2837ce8a.png)
![Screenshot_20211217_122402](https://user-images.githubusercontent.com/4151368/146537602-e2460ae5-33c3-4775-9825-8dbbd7a24226.png)
![Screenshot_20211217_122416](https://user-images.githubusercontent.com/4151368/146537622-80decd5c-e800-4c53-ba3f-b4caa37cde33.png)
![Screenshot_20211217_122444](https://user-images.githubusercontent.com/4151368/146537671-8110cd25-b112-405f-9971-01ec78d7c3e2.png)

**Comment by AlexW00** [comment]
Thank you for the report. Fixed in 1feb5c201be88851aaeae90431ed47e03b206f92, change is now live.
